assignOwner:
  Affix: cipchk
  Alert: vthinkxie
  Anchor: cipchk
  AutoComplete: hsuanxyz
  Avatar: hsuanxyz
  BackTop: cipchk
  Badge: hsuanxyz
  Breadcrumb: wendzhue
  Button: vthinkxie
  Empty: wendzhue
  Calendar: wenqi73
  Card: vthinkxie
  Carousel: wendzhue
  Cascader: wendzhue
  Comment: hsuanxyz
  Checkbox: vthinkxie
  Collapse: vthinkxie
  DatePicker: wenqi73
  Divider: vthinkxie
  Descriptions: wendzhue
  Drawer: hsuanxyz
  Dropdown: vthinkxie
  Form: vthinkxie
  Grid: vthinkxie
  Icon: wendzhue
  Input: vthinkxie
  InputNumber: vthinkxie
  Layout: vthinkxie
  List: cipchk
  Mention: hsuanxyz
  Menu: vthinkxie
  Message: wendzhue
  Modal: hsuanxyz
  Notification: wendzhue
  PageHeader: hsuanxyz
  Pagination: vthinkxie
  Popconfirm: wendzhue
  Popover: wendzhue
  Progress: wendzhue
  Radio: vthinkxie
  Rate: wendzhue
  Select: vthinkxie
  Slider: wendzhue
  Spin: vthinkxie
  Statistic: wendzhue
  Steps: hsuanxyz
  Skeleton: wenqi73
  Switch: vthinkxie
  Table: vthinkxie
  Tabs: vthinkxie
  Tag: hsuanxyz
  TimePicker: wenqi73
  Timeline: wendzhue
  Tooltip: wendzhue
  Transfer: cipchk
  Tree: simplejason
  TreeSelect: hsuanxyz
  Typography: hsuanxyz
  Upload: cipchk
