version: 2

references:
  container_config: &container_config
    environment:
      CHROME_BIN: /usr/bin/google-chrome
      NG_CLI_ANALYTICS: ci
    docker:
      - image: circleci/node:12.13.1-browsers
    working_directory: ~/ng-zorro-antd

  attach_workspace: &attach_workspace
    attach_workspace:
      at: ~/ng-zorro-antd

  workflow: &workflow
    jobs:
      - setup
#      - lib:
#          requires:
#            - setup
#      - build:
#          requires:
#            - lib
      - test:
          requires:
            - setup
      - schematics:
          requires:
            - setup
      - lint:
          requires:
            - setup
      - integration-cli:
          requires:
            - setup
      - integration-webpack:
          requires:
            - setup
      - integration-rollup:
          requires:
            - setup
jobs:
  setup:
    <<: *container_config
    steps:
      - checkout
      - run: node -v
      - run: npm -v
      - run: npm install
      - run:
          command: |
            set +eo
            npm ls
            true
      - persist_to_workspace:
          root: ~/ng-zorro-antd
          paths:
            - node_modules
  lib:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: npm run build:lib
      - persist_to_workspace:
          root: ~/ng-zorro-antd
          paths:
            - publish
#  build:
#    <<: *container_config
#    steps:
#      - checkout
#      - *attach_workspace
#      - run: npm run build
  test:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: npm run test
  schematics:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: npm run test:schematics
  lint:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: npm run lint
  integration-cli:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: sudo apt install rsync
      - run: npm run integration-cli
  integration-webpack:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: sudo apt install rsync
      - run: npm run integration-webpack
  integration-rollup:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: sudo apt install rsync
      - run: npm run integration-rollup

workflows:
  version: 2
  build_workflow:
    <<: *workflow
