/**
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/LICENSE
 */

import { Component, DebugElement } from '@angular/core';
import { ComponentFixture, TestBed } from '@angular/core/testing';
import { By } from '@angular/platform-browser';
import { PRIMARY_OUTLET, provideRouter, Router, RouterOutlet, Routes } from '@angular/router';

import { vi } from 'vitest';

import { testDirectionality } from 'ng-zorro-antd/core/testing';
import { NzSafeAny } from 'ng-zorro-antd/core/types';
import { provideNzIconsTesting } from 'ng-zorro-antd/icon/testing';

import { NzBreadCrumbItemComponent } from './breadcrumb-item.component';
import { NzBreadCrumbComponent } from './breadcrumb.component';
import { NzBreadCrumbModule } from './breadcrumb.module';
import { NzDemoBreadcrumbBasicComponent } from './demo/basic';
import { NzDemoBreadcrumbDropdownComponent } from './demo/dropdown';
import { NzDemoBreadcrumbSeparatorComponent } from './demo/separator';

describe('breadcrumb', () => {
  describe('basic', () => {
    let fixture: ComponentFixture<NzDemoBreadcrumbBasicComponent>;
    let items: DebugElement[];
    let breadcrumb: DebugElement;

    beforeEach(() => {
      fixture = TestBed.createComponent(NzDemoBreadcrumbBasicComponent);
      items = fixture.debugElement.queryAll(By.directive(NzBreadCrumbItemComponent));
      breadcrumb = fixture.debugElement.query(By.directive(NzBreadCrumbComponent));
    });

    it('should have correct style', () => {
      fixture.detectChanges();
      expect(items.every(item => item.nativeElement.firstElementChild!.classList.contains('ant-breadcrumb-link'))).toBe(
        true
      );
      expect(items.every(item => item.nativeElement.children[1].classList.contains('ant-breadcrumb-separator'))).toBe(
        true
      );
      expect(breadcrumb.nativeElement.classList.contains('ant-breadcrumb')).toBe(true);
    });
  });

  describe('dropdown', () => {
    let fixture: ComponentFixture<NzDemoBreadcrumbDropdownComponent>;
    let items: DebugElement[];

    beforeEach(() => {
      fixture = TestBed.createComponent(NzDemoBreadcrumbDropdownComponent);
      items = fixture.debugElement.queryAll(By.directive(NzBreadCrumbItemComponent));
    });

    it('should dropdown work', () => {
      fixture.detectChanges();

      const dropdownElement = items[2];
      expect((dropdownElement.nativeElement as HTMLElement).querySelector('.ant-dropdown-trigger')).not.toBe(null);
    });
  });

  describe('separator', () => {
    let fixture: ComponentFixture<NzDemoBreadcrumbSeparatorComponent>;
    let items: DebugElement[];
    let breadcrumbs: DebugElement[];

    beforeEach(() => {
      TestBed.configureTestingModule({
        providers: [provideNzIconsTesting()]
      });
    });

    beforeEach(() => {
      fixture = TestBed.createComponent(NzDemoBreadcrumbSeparatorComponent);
      items = fixture.debugElement.queryAll(By.directive(NzBreadCrumbItemComponent));
      breadcrumbs = fixture.debugElement.queryAll(By.directive(NzBreadCrumbComponent));
    });

    it('should nzSeparator work', () => {
      fixture.detectChanges();
      expect(items.every(item => item.nativeElement.firstElementChild!.classList.contains('ant-breadcrumb-link'))).toBe(
        true
      );
      expect(items.every(item => item.nativeElement.children[1].classList.contains('ant-breadcrumb-separator'))).toBe(
        true
      );
      expect(breadcrumbs.every(breadcrumb => breadcrumb.nativeElement.classList.contains('ant-breadcrumb'))).toBe(true);
      expect(items[0].nativeElement.children[1].innerText.indexOf('>') > -1).toBe(true);
      expect(items[3].nativeElement.children[1].firstElementChild!.classList.contains('anticon-arrow-right')).toBe(
        true
      );
    });
  });

  describe('auto generated', () => {
    let fixture: ComponentFixture<NzBreadcrumbAutoGenerateDemoComponent>;
    let router: Router;
    let breadcrumb: DebugElement;

    it('should auto generating work', async () => {
      TestBed.configureTestingModule({
        providers: [provideRouter(routes)]
      });

      fixture = TestBed.createComponent(NzBreadcrumbAutoGenerateDemoComponent);
      breadcrumb = fixture.debugElement.query(By.directive(NzBreadCrumbComponent));

      router = TestBed.inject(Router);
      router.initialNavigation();

      // Should generate 2 breadcrumbs when reaching out of the `data` scope.
      await router.navigate(['one', 'two', 'three', 'four']);
      await stabilize(fixture);
      expect(breadcrumb.componentInstance.breadcrumbs.length).toBe(2);

      // TODO: pending this test because of Angular's bug: https://github.com/angular/angular/issues/25837
      // const items = fixture.debugElement.queryAll(By.directive(NzBreadCrumbItemComponent));
      // dispatchMouseEvent(items[1].nativeElement.querySelector('a'), 'click');
      // await flushFixture(fixture);
      // expect(breadcrumb.componentInstance.breadcrumbs.length).toBe(1);

      // Should generate breadcrumbs correctly.
      await router.navigate(['one', 'two', 'three']);
      await stabilize(fixture);
      expect(breadcrumb.componentInstance.breadcrumbs.length).toBe(2);
      await router.navigate(['one', 'two']);
      await stabilize(fixture);
      expect(breadcrumb.componentInstance.breadcrumbs.length).toBe(1);

      // Shouldn't generate breadcrumb at all.
      await router.navigate(['one']);
      await stabilize(fixture);
      expect(breadcrumb.componentInstance.breadcrumbs.length).toBe(0);

      await router.navigate(['/']);
      await stabilize(fixture);
      await router.navigate([{ outlets: { nonPrimary: ['one', 'two'] } }]);
      await stabilize(fixture);
      expect(router.url).toBe('/(nonPrimary:one/two)');
    });

    it('should route data breadcrumb label work', async () => {
      TestBed.configureTestingModule({
        providers: [provideRouter(customRouteLabelRoutes)]
      });

      fixture = TestBed.createComponent(NzBreadcrumbRouteLabelDemoComponent);
      breadcrumb = fixture.debugElement.query(By.directive(NzBreadCrumbComponent));

      router = TestBed.inject(Router);
      router.initialNavigation();

      // Should nzRouteLabel value is 'customBreadcrumb'
      await stabilize(fixture);
      expect(breadcrumb.componentInstance.nzRouteLabel).toBe('customBreadcrumb');

      // Should generate 2 breadcrumbs when reaching out of the `data` scope.
      await router.navigate(['one', 'two', 'three', 'four']);
      await stabilize(fixture);
      expect(breadcrumb.componentInstance.breadcrumbs.length).toBe(2);
      expect(breadcrumb.componentInstance.breadcrumbs[0].label).toBe('Layer 2');
      expect(breadcrumb.componentInstance.breadcrumbs[1].label).toBe('Layer 3');
    });

    it('should [nzRouteLabelFn] work', async () => {
      TestBed.configureTestingModule({
        providers: [provideRouter(customRouteLabelRoutes)]
      });

      fixture = TestBed.createComponent(NzBreadcrumbRouteLabelWithCustomFnDemoComponent);
      breadcrumb = fixture.debugElement.query(By.directive(NzBreadCrumbComponent));

      router = TestBed.inject(Router);
      router.initialNavigation();

      // Should nzRouteLabel value is 'customBreadcrumb'
      await stabilize(fixture);
      expect(breadcrumb.componentInstance.nzRouteLabel).toBe('customBreadcrumb');

      // Should generate 2 breadcrumbs when reaching out of the `data` scope.
      await router.navigate(['one', 'two', 'three', 'four']);
      await stabilize(fixture);
      expect(breadcrumb.componentInstance.breadcrumbs.length).toBe(2);
      expect(breadcrumb.componentInstance.breadcrumbs[0].label).toBe('Layer 2 Layer 2');
      expect(breadcrumb.componentInstance.breadcrumbs[1].label).toBe('Layer 3 Layer 3');
    });

    it('should [nzRouteFn] work', async () => {
      TestBed.configureTestingModule({
        providers: [provideRouter(customRouteLabelRoutes)]
      });

      fixture = TestBed.createComponent(NzBreadcrumbRouteWithCustomFnDemoComponent);
      breadcrumb = fixture.debugElement.query(By.directive(NzBreadCrumbComponent));

      router = TestBed.inject(Router);
      router.initialNavigation();

      // Breadcrumb should contain added params by nzRouteFn
      await router.navigate(['one', 'two']);
      await stabilize(fixture);
      expect(breadcrumb.componentInstance.breadcrumbs[0].url).toContain('active=true');
    });

    it('should route data breadcrumb navigate work', async () => {
      TestBed.configureTestingModule({
        providers: [provideRouter(customRouteLabelRoutes)]
      });

      fixture = TestBed.createComponent(NzBreadcrumbRouteLabelDemoComponent);
      breadcrumb = fixture.debugElement.query(By.directive(NzBreadCrumbComponent));

      router = TestBed.inject(Router);
      router.initialNavigation();

      await stabilize(fixture);
      expect(breadcrumb.componentInstance.nzRouteLabel).toBe('customBreadcrumb');

      await router.navigate(['one', 'two', 'three', 'four']);
      await stabilize(fixture);

      fixture.debugElement.query(By.css('a')).nativeElement.click();
      await stabilize(fixture);
      expect(router.url).toBe('/one/two');
    });

    it('should raise error when RouterModule is not included', () => {
      expect(() => {
        fixture = TestBed.createComponent(NzBreadcrumbAutoGenerateErrorDemoComponent);
        fixture.detectChanges();
      }).toThrowError();
    });
  });

  testDirectionality(() => NzDemoBreadcrumbBasicComponent, By.directive(NzBreadCrumbComponent), 'ant-breadcrumb');
});

async function stabilize(fixture: ComponentFixture<NzSafeAny>): Promise<void> {
  fixture.detectChanges();
  await fixture.whenStable();
  fixture.detectChanges();
}

@Component({
  imports: [RouterOutlet, NzBreadCrumbModule],
  selector: 'nz-test-breadcrumb',
  template: `
    <nz-breadcrumb nzAutoGenerate />
    <router-outlet />
    <router-outlet name="nonPrimary" />
  `
})
class NzBreadcrumbAutoGenerateDemoComponent {}

@Component({
  imports: [RouterOutlet, NzBreadCrumbModule],
  template: `
    <nz-breadcrumb nzAutoGenerate nzRouteLabel="customBreadcrumb" />
    <router-outlet />
  `
})
class NzBreadcrumbRouteLabelDemoComponent {}

@Component({
  imports: [RouterOutlet, NzBreadCrumbModule],
  template: `
    <nz-breadcrumb nzAutoGenerate nzRouteLabel="customBreadcrumb" [nzRouteLabelFn]="labelFn" />
    <router-outlet />
  `
})
class NzBreadcrumbRouteLabelWithCustomFnDemoComponent {
  labelFn = (label: string): string => (label ? `${label} ${label}` : '');
}

@Component({
  imports: [RouterOutlet, NzBreadCrumbModule],
  template: `
    <nz-breadcrumb nzAutoGenerate nzRouteLabel="customBreadcrumb" [nzRouteFn]="routeFn" />
    <router-outlet />
  `
})
class NzBreadcrumbRouteWithCustomFnDemoComponent {
  routeFn = (route: string): string => `${route};active=true`;
}

@Component({
  imports: [NzBreadCrumbModule],
  template: '<nz-breadcrumb [nzAutoGenerate]="true" />'
})
class NzBreadcrumbAutoGenerateErrorDemoComponent {}

@Component({
  template: 'empty'
})
class NzBreadcrumbNullComponent {}

const routes: Routes = [
  {
    path: 'one',
    component: NzBreadcrumbAutoGenerateDemoComponent,
    data: {
      breadcrumb: ''
    },
    children: [
      {
        path: 'two',
        component: NzBreadcrumbNullComponent,
        data: {
          breadcrumb: 'Layer 2'
        },
        children: [
          {
            path: 'three',
            component: NzBreadcrumbNullComponent,
            data: {
              breadcrumb: 'Layer 3'
            },
            children: [
              {
                path: 'four',
                component: NzBreadcrumbNullComponent,
                data: {
                  breadcrumb: ''
                }
              }
            ]
          }
        ]
      }
    ]
  },
  // Should only work for the primary outlet.
  {
    path: 'one',
    outlet: 'nonPrimary',
    component: NzBreadcrumbAutoGenerateDemoComponent,
    data: {
      breadcrumb: ''
    },
    children: [
      {
        path: 'two',
        component: NzBreadcrumbNullComponent,
        data: {
          breadcrumb: 'Layer 2'
        }
      }
    ]
  }
];

const customRouteLabelRoutes: Routes = [
  {
    path: 'one',
    component: NzBreadcrumbRouteLabelDemoComponent,
    data: {
      customBreadcrumb: ''
    },
    children: [
      {
        path: 'two',
        component: NzBreadcrumbNullComponent,
        data: {
          customBreadcrumb: 'Layer 2'
        },
        children: [
          {
            path: 'three',
            component: NzBreadcrumbNullComponent,
            data: {
              customBreadcrumb: 'Layer 3'
            },
            children: [
              {
                path: 'four',
                component: NzBreadcrumbNullComponent,
                data: {
                  customBreadcrumb: ''
                }
              }
            ]
          }
        ]
      }
    ]
  }
];

describe('breadcrumb', () => {
  let fixture: ComponentFixture<NzBreadCrumbComponent>;
  let component: NzBreadCrumbComponent;

  beforeEach(() => {
    fixture = TestBed.createComponent(NzBreadCrumbComponent);
    component = fixture.componentInstance;
  });

  it('should have correct value for nextUrl', () => {
    vi.spyOn(component, 'nzRouteFn');
    const mockRoute = {
      children: [
        {
          outlet: PRIMARY_OUTLET,
          snapshot: {
            url: [],
            data: {
              breadcrumb: 'breadcrumb'
            }
          },
          children: []
        }
      ]
    };

    component['getBreadcrumbs'](mockRoute as NzSafeAny, 'mockUrl', []);

    expect(component.nzRouteFn).toHaveBeenCalledWith('mockUrl');
  });
});
